@file:OptIn(ExperimentalKotlinGradlePluginApi::class)

import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi

plugins {
    kotlin("multiplatform") version "2.2.0"
    id("com.vanniktech.maven.publish") version "0.29.0"
    id("maven-publish")
    signing
}

group = "io.github.dingyi222666"
version = "1.0.3"

val runNativeHostTests = providers.gradleProperty("runNativeHostTests")
    .map { it.equals("true", ignoreCase = true) }
    .orElse(false)

// The builtin overlay (Lua 5.3/5.4 stdlib, AndroLua, Android framework index) lives as plain
// files under src/commonMain/resources so it stays reviewable and diffable. Only Kotlin/JVM can
// read classpath resources, so this task mirrors the exact same bytes into a generated Kotlin
// source that every target compiles in. Generating removes the hand-maintained per-target copies
// that used to drift out of sync with the real overlay.
val generatedOverlayMirrorDir = layout.buildDirectory.dir("generated/builtinOverlayMirror/kotlin")

val generateBuiltinOverlayMirror = tasks.register("generateBuiltinOverlayMirror") {
    group = "build"
    description = "Embeds src/commonMain/resources overlay files into a generated Kotlin source"

    val resourcesDir = layout.projectDirectory.dir("src/commonMain/resources")
    val outputDir = generatedOverlayMirrorDir
    inputs.dir(resourcesDir).withPropertyName("overlayResources")
    outputs.dir(outputDir).withPropertyName("generatedSources")

    doLast {
        val root = resourcesDir.asFile
        val entries = root.walkTopDown()
            .filter { it.isFile && it.name != ".DS_Store" }
            .map { file ->
                val key = "/" + file.relativeTo(root).invariantSeparatorsPath
                key to file.readText()
            }
            .sortedBy { it.first }
            .toList()

        fun quote(value: String): String = buildString(value.length + 16) {
            append('"')
            value.forEach { char ->
                when (char) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '$' -> append("\\$")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(char)
                }
            }
            append('"')
        }

        val target = outputDir.get().asFile
            .resolve("io/github/dingyi222666/luaparser/semantic/workspace/std")
        target.mkdirs()
        target.resolve("BuiltinOverlayResourceMirror.kt").writeText(
            buildString {
                appendLine("// Generated by the generateBuiltinOverlayMirror Gradle task. Do not edit.")
                appendLine("// Source of truth: src/commonMain/resources")
                appendLine("package io.github.dingyi222666.luaparser.semantic.workspace.std")
                appendLine()
                appendLine("internal object BuiltinOverlayResourceMirror {")
                appendLine("    val resources: Map<String, String> = linkedMapOf(")
                entries.forEachIndexed { index, (key, content) ->
                    append("        ")
                    append(quote(key))
                    append(" to ")
                    append(quote(content))
                    appendLine(if (index == entries.lastIndex) "" else ",")
                }
                appendLine("    )")
                appendLine("}")
            }
        )
    }
}

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    macosX64()
    macosArm64()
    linuxArm64()
    linuxX64()
    mingwX64()

    js {
        browser {
            testTask {
                useKarma {
                    useChromeHeadless()
                    webpackConfig.cssSupport {
                        enabled.set(true)
                    }
                }
            }
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuiltinOverlayMirror)
            dependencies {
                implementation(kotlin("stdlib"))
                implementation(kotlin("test"))

            }
        }
        commonTest {
            dependencies {
                implementation(kotlin("test"))
                implementation(kotlin("test-annotations-common"))
            }
        }

        jvmMain {
            dependencies {
                implementation("org.eclipse.lsp4j:org.eclipse.lsp4j:0.23.1")
                implementation("org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.23.1")
            }
        }

        jvmTest {
            dependencies {
                implementation(kotlin("test-junit"))
            }
            // add java to src
        }

        jsTest {
            dependencies {
                implementation(kotlin("test-js"))
            }
        }

        nativeTest {
            dependencies {
                //  implementation(kotlin("test-native"))
            }
        }
    }

    jvmToolchain(11)
}

tasks.named("linkDebugTestMingwX64") {
    onlyIf("Enable Windows Kotlin/Native host test linking with -PrunNativeHostTests=true") {
        runNativeHostTests.get()
    }
}

tasks.named("mingwX64Test") {
    onlyIf("Enable Windows Kotlin/Native host test execution with -PrunNativeHostTests=true") {
        runNativeHostTests.get()
    }
}

// Parallel JVM tests: soft maxParallelForks=5; Windows CI hard-caps CPU via affinity script
tasks.withType<Test>().configureEach {
    maxParallelForks = 5
    // Avoid one hung suite blocking the whole fork forever without bound
    // (individual tests still use JUnit defaults unless annotated)
}

tasks.register<JavaExec>("runLuaLanguageServer") {
    group = "application"
    description = "Run the Lua language server over stdio"
    classpath = files(tasks.named("jvmJar"), configurations.getByName("jvmRuntimeClasspath"))
    mainClass.set("io.github.dingyi222666.luaparser.lsp.LuaLanguageServerLauncherKt")
    standardInput = System.`in`
}

mavenPublishing {
    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.S01)

    signAllPublications()

    coordinates("io.github.dingyi222666", "luaparser", "1.0.3")

    pom {
        name.set("luaparser")
        description.set("A Lua 5.3 Lexer & Parser written in pure Kotlin.")
        inceptionYear.set("2023")
        url.set("https://github.com/dingyi222666/luaparser")
        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                distribution.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("dingyi222666")
                name.set("dingyi222666")
                url.set("https://github.com/dingyi222666")
            }
        }
        scm {
            url.set("https://github.com/dingyi222666/lua-parser")
            connection.set("scm:git:git://github.com/dingyi222666/lua-parser.git")
            developerConnection.set("scm:git:ssh://git@github.com/dingyi222666/lua-parser.git")
        }
    }
}
